name: Build an extension defined by the user

on:
  workflow_dispatch:
    inputs:
      extension:
        description: "The extension name"
        required: true
        type: string

jobs:
  build_extensions:
    uses: ./.github/workflows/build_extension.yml
    with:
      extension: ${{ inputs.extension }}
